Databases:
  MyCustomDB:
    - audio_data/{uri}.wav

Protocols:
  MyCustomDB:
    SpeakerDiarization:
      MyProtocol:
        scope: file
        train:
            uri: lists/train.list.txt
            annotation: rttm/{uri}.rttm
            annotated: uem/{uri}.uem
        development:
            uri: lists/dev.list.txt
            annotation: rttm/{uri}.rttm
            annotated: uem/{uri}.uem
        test:
            uri: lists/test.list.txt
            annotation: rttm/{uri}.rttm
            annotated: uem/{uri}.uem
