Databases:
  MyCustomDB:
    - audio_data/{uri}.wav

Protocols:
  MyCustomDB:
    SpeakerDiarization:
      MyProtocol:
        scope: file
        train:
            uri: lists/train.list
            annotation: rttm/{uri}.rttm
        development:
            uri: lists/dev.list
            annotation: rttm/{uri}.rttm
        test:
            uri: lists/test.list
            annotation: rttm/{uri}.rttm
