Databases:
  MyCustomDB:
    - audio_data/{uri}.wav

Protocols:
  MyCustomDB:
    SpeakerDiarization:
      MyProtocol:
        scope: file
        train:
            uri: lists/train.lst
            annotation: rttm/{uri}.rttm
        development:
            uri: lists/dev.lst
            annotation: rttm/{uri}.rttm
        test:
            uri: lists/test.lst
            annotation: rttm/{uri}.rttm
