Databases:
  MyDatabase:
    audio: ../audio_data/{uri}.wav

Protocols:
  MyDatabase:
    SpeakerDiarization:
      mini:
        train:
          uri: ../lists/train.list.txt
          annotation: ../audio_data/{uri}.rttm
        development:
          uri: ../lists/dev.list.txt
          annotation: ../audio_data/{uri}.rttm
        test:
          uri: ../lists/test.list.txt
          annotation: ../audio_data/{uri}.rttm

      full:     # 전체 데이터셋용 (향후 확장)
        train:
          uri: ../lists/train.full.txt
          annotation: ../audio_data/{uri}.rttm
        development:
          uri: ../lists/dev.full.txt
          annotation: ../audio_data/{uri}.rttm
        test:
          uri: ../lists/test.full.txt
          annotation: ../audio_data/{uri}.rttm
