Databases:
  MyDatabase:
    audio: /content/pyannote-finetuning-data/audio_data/{uri}.wav

Protocols:
  MyDatabase:
    SpeakerDiarization:
      mini:
        train:
          uri: /content/pyannote-finetuning-data/lists/train.list.txt
          annotation: /content/pyannote-finetuning-data/audio_data/{uri}.rttm
        development:
          uri: /content/pyannote-finetuning-data/lists/dev.list.txt
          annotation: /content/pyannote-finetuning-data/audio_data/{uri}.rttm
        test:
          uri: /content/pyannote-finetuning-data/lists/test.list.txt
          annotation: /content/pyannote-finetuning-data/audio_data/{uri}.rttm

      full:
        train:
          uri: /content/pyannote-finetuning-data/lists/train.full.txt
          annotation: /content/pyannote-finetuning-data/audio_data/{uri}.rttm
        development:
          uri: /content/pyannote-finetuning-data/lists/dev.full.txt
          annotation: /content/pyannote-finetuning-data/audio_data/{uri}.rttm
        test:
          uri: /content/pyannote-finetuning-data/lists/test.full.txt
          annotation: /content/pyannote-finetuning-data/audio_data/{uri}.rttm
